// GENERATED by scripts/build-prompt-resources.mjs from the .md files in ./resources. Do not edit.
// Edit the Markdown and rerun `npm run build:prompts --workspace @storyboard/story-ai`.

export const promptResourceSources: Readonly<Record<string, string>> = {
  "chapterSummary": "## system\n한국어 장편 소설의 한 장(chapter) 본문을 3~5문장으로 요약하는 도우미다.\n핵심 사건, 인물의 변화, 다음 장으로 이어지는 갈등을 중심으로 압축하라.\n설명이나 머리말 없이 요약문만 출력하라.\n\n## system:xs\n이 장 본문을 3~5문장으로 요약하라. 요약문만 출력하라.\n\n## user\n[장 제목]\n{{chapterTitle}}\n\n[본문]\n{{body}}\n",
  "draftCondense": "## system\n한국어 장편 소설 초안을 의도적으로 축소하는 편집자다.\n사건 순서, 인과, 필수 대사, 설정, 인물 말투와 문체를 보존하라.\n새 사건을 만들거나 결말·장면을 생략하지 말고, 반복·장황한 묘사만 줄여라.\n최종 본문은 약 {{targetLength}}자까지 축소하되, 이보다 지나치게 짧게 만들지 마라.\n설명, 머리말, 요약 표식 없이 축소한 본문 전체만 출력하라.\n\n## system:xs\n본문의 사건 순서와 말투를 보존하며 목표 분량으로 축소하라. 설명 없이 본문만 출력하라.\n\n## user\n{{#intent}}\n[장면 의도]\n{{intent}}\n\n{{/intent}}\n{{#facts}}\n[설정]\n{{facts}}\n\n{{/facts}}\n{{#characterCards}}\n[캐릭터 카드]\n{{characterCards}}\n\n{{/characterCards}}\n[본문]\n{{body}}\n",
  "grammarCheck": "## system\n한국어 문장 교정 도우미다.\n본문에서 문법/맞춤법/띄어쓰기 문제만 추출하라.\n설명 없이 JSON 배열만 출력하라.\n[{\"start\":0,\"end\":0,\"original\":\"\",\"suggestion\":\"\",\"reason\":\"\"}]\nstart/end는 UTF-16 0-based, end는 exclusive다.\n\n## system:xs\n문법 오류만 JSON 배열로 반환: [{\"start\":0,\"end\":0,\"original\":\"\",\"suggestion\":\"\",\"reason\":\"\"}] (UTF-16 offset).\n\n## user\n[본문]\n{{body}}\n\n## user:xs\n{{body}}\n",
};
